#!/bin/bash

debuglog=true
set -x


function finishProc {
  # Your cleanup code here
  echo "Cleaning up"
  killall -q /usr/bin/python  python
  # killall -q chromium-browser
}

trap finishProc EXIT SIGINT SIGTERM

projDir="$HOME/pithy"

cd "$projDir"

echo "debuglog is <$debuglog>"

if [ ! $debuglog ]; then
  ./websrvd.py &
  ./runBrowser
else
  ./websrvd.py &
  ./runBrowser &
  # lf="logs/debug_`date -I | sed 's/-//g'`.log"
  # tail -f "$lf"
fi
