#!/bin/bash

debuglog=true
set -x


function finishProc {
  # Your cleanup code here
  echo "Cleaning up"
  killall -q /usr/bin/python chromium-browser python
}

trap finishProc EXIT SIGINT SIGTERM

projDir="$HOME/git/pithy"

cd "$projDir"

if [ ! $debuglog ]; then
  rubustat_web_interface.py &
  ./runBrowser
else 
  rubustat_web_interface.py &
  ./runBrowser &
  lf="logs/debug_`date -I | sed 's/-//g'`.log"
  tail -f "$lf"
fi






