#!/bin/sh


chromium-browser --noerrdialogs --kiosk --incognito --disable-translate 0.0.0.0:7000 >/dev/null 2>&1
# chromium-browser --noerrdialogs --kiosk --incognito --disable-translate 0.0.0.0:7000 >/dev/null 2>&1
