#!/bin/sh

export DISPLAY=:0.0
export HOME=/home/pi


# Production config -- run in Kiosk mode
chromium-browser --noerrdialogs  --kiosk --incognito --disable-translate 0.0.0.0:7000 >/dev/null 2>&1

# Run without Kiosk mode, for debugging
#chromium-browser --noerrdialogs  --incognito --disable-translate 0.0.0.0:7000 >/dev/null 2>&1
