#! /usr/bin/env python3

"""
Writes a TEMP\nHUMID tuple into the testing file to simulate
temperature readings
"""

#
# Pipes two values into tfile

from sys import *
from pdb import set_trace as bp

import sys
humid = 50
tfile = "tfile"


# bp()

def pusage(str):
    print("Usage: {} <temp<float>> [<humid(int)>]".format(argv[0]),
          file=sys.stderr)
    sys.exit(9)


if len(argv) < 2:
    pusage("no params supplied")

if len(argv) >= 2:
    try:
        temp = float(argv[1])
    except ValueError:
        pusage("params must be numeric")
if len(argv) == 3:
    humid = int(argv[2])
if len(argv) > 3:
        pusage("only max two parms allowed")


outf = open(tfile, "w")

print("{:f}\n{:d}".format(temp, humid), file=outf)
outf.close()

print("Wrote temp of {:f} and humid of {:d}".format(temp, humid))
sys.exit(0)
